# Missing values in Firmographic Dataset

---
### <i>Changelogs:</i>

  Name  |  Date  |   Description
- **Bao Tran**  |  03/17  |  Create notebook, testing missing values.Reorganize folder and files.
- **Kiet Vu**  |  03/17  | Minor Editing, adding column names that has >80% missing values.

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
# missing_values_table function

def missing_values_table(df):
    mis_val = df.isnull().sum()
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)
    if str(mis_val_table_ren_columns.shape[0]) == '1':
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There is " + str(mis_val_table_ren_columns.shape[0]) +
            " column that have missing values.")
    else:
        print("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
            " columns that have missing values.")
    return mis_val_table_ren_columns

In [8]:
# Firmographic file
df_firmographic = pd.read_csv("Clean Data/firmographic_clean_20230314.csv", low_memory=False)
df_firmographic.head(15)

,unique_identifier,B2B_ADDR_ZIP5,B2B_ADDR_STATE,B2B_ACCEPT_CREDIT_CARD_FLAG,B2B_ACCOUNTING_EXPENSE_CODE,B2B_AD_SIZE,B2B_ADVERTISING_EXPENSE_CODE,B2B_ASSET_FLAG,B2B_BANKRUPTCY_DATE,B2B_BANKRUPTCY_FLAG,...,B2B_TOT_SALES_VOLUME,B2B_TRANSACTION_CODE,B2B_TRANSACTION_TYPE,B2B_TRUE_FRNCHSE_FLAG,B2B_UTILITY_CODE,B2B_WEALTH_FLAG,B2B_WHITE_COLLAR_FLAG,B2B_WHITE_COLLAR_PRCNT,B2B_YEAR_SIC_ADD,CAC_SEGMENT
0,0001230a214b39e0e5c463bfe440fb15,44240.0,OH,NaN,C,A,A,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,D,NaN,NaN,25.0,201801.0,Manufacturing
1,000345e997e72b61b990d2689c76427f,15218.0,PA,NaN,D,A,C,NaN,NaN,NaN,...,NaN,A,NaN,NaN,B,NaN,1.0,99.0,198405.0,Business and Finance
2,0003c4d7aeb24f319f0d7c6ddb60bb8f,44067.0,OH,ADMV,C,B,B,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,A,1.0,NaN,16.0,201909.0,Personal Services
3,00082675e86a9f3cf5fdcc5d4cd9114d,60618.0,IL,NaN,D,NaN,B,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,C,NaN,NaN,21.0,199104.0,Blue Collar Work
4,00095201031df44962513f378842d521,61111.0,IL,DMV,A,A,A,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,A,NaN,1.0,83.0,201303.0,General Merchandise
5,000a04481ee5acbb856a7c485a67423a,62526.0,IL,NaN,E,A,D,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,D,NaN,1.0,50.0,201902.0,Personal Services
6,000a1fe8f9d0caf306b805de359b6947,14472.0,NY,NaN,G,B,F,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,D,NaN,1.0,54.0,202208.0,Wholesale
7,000bee0b537b676a975a15999776581f,2110.0,MA,NaN,C,B,C,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,A,NaN,NaN,10.0,202011.0,Food and Dining
8,000c88d34beda722f7b559bb056b7809,78064.0,TX,ADMV,A,A,A,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,A,NaN,NaN,29.0,201303.0,Hotels and Educational Boarding
9,000cc270c1cc3f09a4a80c2489ce4bac,8401.0,NJ,ADMV,E,A,E,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,B,NaN,NaN,10.0,200309.0,Food and Dining
10,000ea4af96ab938b2612e0b39738e334,7032.0,NJ,ADMV,D,B,B,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,D,NaN,NaN,29.0,201902.0,Manufacturing
11,000f645a52095f72ec723133e2b0092c,45601.0,OH,NaN,D,NaN,A,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,B,NaN,1.0,97.0,202007.0,"Public, Health, and Social Services"
12,00109796f3c34d87f1ff2778498a8016,18330.0,PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,0.0,201909.0,Unknown
13,0012e632be3d04fab35771fe3fb6db31,60467.0,IL,NaN,A,NaN,A,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,A,1.0,NaN,16.0,201804.0,Personal Services
14,00130d1949e17227076bc7e4f75139af,43026.0,OH,NaN,A,NaN,A,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,A,NaN,1.0,67.0,202002.0,Personal Services

In [4]:
# Return the columns' names and the number of missing values
missing_values_table(df_firmographic)

Your selected dataframe has 101 columns.
There are 96 columns that have missing values.

                         Missing Values  % of Total Values
B2B_FORTUNE_RANK                  59849               99.9
B2B_BANKRUPTCY_DATE               59824               99.9
B2B_BANKRUPTCY_FLAG               59824               99.9
B2B_FOREIGN_PARENT_FLAG           59799               99.9
B2B_GOVERNMENT_FLAG               59191               98.8
...                                 ...                ...
B2B_SIC_CODE                          1                0.0
B2B_NUM_TENANATS                      1                0.0
B2B_PRIMARY_SIC                       1                0.0
B2B_PRIMARY_SIC_DESCRIP               1                0.0
B2B_ADDR_ZIP5                         1                0.0

[96 rows x 2 columns]

In [9]:
# Get the columns with > 80% missing
missing_df = missing_values_table(df_firmographic);
missing_columns = list(missing_df[missing_df['% of Total Values'] > 80].index)
if len(missing_columns) == 1: 
  print('We will remove %d column.' % len(missing_columns))
else:
  print('We will remove %d columns.' % len(missing_columns))

Your selected dataframe has 101 columns.
There are 96 columns that have missing values.
We will remove 31 columns.

In [12]:
# column names that have > 80% missing values
missing_columns

['B2B_FORTUNE_RANK',
 'B2B_BANKRUPTCY_DATE',
 'B2B_BANKRUPTCY_FLAG',
 'B2B_FOREIGN_PARENT_FLAG',
 'B2B_GOVERNMENT_FLAG',
 'B2B_RESTAURANT_SRVCE_TYPE',
 'B2B_IMPORT_EXPORT_FLAG',
 'B2B_HOME_FLAG',
 'B2B_ASSET_FLAG',
 'B2B_TOT_SALES',
 'B2B_TOT_SALES_VOLUME',
 'B2B_TOT_EMPLOYEE_SIZE',
 'B2B_TOT_EMPLOYEE_NUM',
 'B2B_TRANSACTION_TYPE',
 'B2B_PUBLIC_INDICATOR',
 'B2B_INDUSTRY_CODE',
 'B2B_FEMALE_OWNED_BUSINESS',
 'B2B_TRANSACTION_CODE',
 'B2B_EXPRESS_UPDATE',
 'B2B_OWN_LEASE_FLAG',
 'B2B_OFFICE_SIZE',
 'B2B_PROFESSIONAL_FLAG',
 'B2B_NAICS4',
 'B2B_NAICS4_DESCRIP',
 'B2B_SECONDARY_SIC_DESCRIP4',
 'B2B_SECONDARY_SIC_CODE4',
 'B2B_BUSINESS_STATUS_CODE',
 'B2B_SECONDARY_SIC_CODE3',
 'B2B_NAICS3_DESCRIP',
 'B2B_SECONDARY_SIC_DESCRIP3',
 'B2B_NAICS3']

In [14]:
#Get new dataframe
df_firmographic_dropped = df_firmographic.drop(list(missing_columns), axis = 1)
df_firmographic_dropped.head(15)

,unique_identifier,B2B_ADDR_ZIP5,B2B_ADDR_STATE,B2B_ACCEPT_CREDIT_CARD_FLAG,B2B_ACCOUNTING_EXPENSE_CODE,B2B_AD_SIZE,B2B_ADVERTISING_EXPENSE_CODE,B2B_BIG_BUSINESS_INDICATOR,B2B_BUSINESS_DESCRIP_FLAG,B2B_BUSINESS_GROW_FLAG,...,B2B_STATE_CODE,B2B_TELECOMMUNICATIONS_CODE,B2B_TENANT_FLAG,B2B_TRUE_FRNCHSE_FLAG,B2B_UTILITY_CODE,B2B_WEALTH_FLAG,B2B_WHITE_COLLAR_FLAG,B2B_WHITE_COLLAR_PRCNT,B2B_YEAR_SIC_ADD,CAC_SEGMENT
0,0001230a214b39e0e5c463bfe440fb15,44240.0,OH,NaN,C,A,A,N,N,C,...,39.0,B,NaN,2.0,D,NaN,NaN,25.0,201801.0,Manufacturing
1,000345e997e72b61b990d2689c76427f,15218.0,PA,NaN,D,A,C,N,N,NaN,...,42.0,D,A,NaN,B,NaN,1.0,99.0,198405.0,Business and Finance
2,0003c4d7aeb24f319f0d7c6ddb60bb8f,44067.0,OH,ADMV,C,B,B,N,N,C,...,39.0,B,A,2.0,A,1.0,NaN,16.0,201909.0,Personal Services
3,00082675e86a9f3cf5fdcc5d4cd9114d,60618.0,IL,NaN,D,NaN,B,N,N,C,...,17.0,C,NaN,2.0,C,NaN,NaN,21.0,199104.0,Blue Collar Work
4,00095201031df44962513f378842d521,61111.0,IL,DMV,A,A,A,N,N,C,...,17.0,A,B,2.0,A,NaN,1.0,83.0,201303.0,General Merchandise
5,000a04481ee5acbb856a7c485a67423a,62526.0,IL,NaN,E,A,D,N,N,C,...,17.0,C,A,2.0,D,NaN,1.0,50.0,201902.0,Personal Services
6,000a1fe8f9d0caf306b805de359b6947,14472.0,NY,NaN,G,B,F,N,Y,C,...,36.0,E,NaN,2.0,D,NaN,1.0,54.0,202208.0,Wholesale
7,000bee0b537b676a975a15999776581f,2110.0,MA,NaN,C,B,C,N,N,C,...,25.0,A,NaN,1.0,A,NaN,NaN,10.0,202011.0,Food and Dining
8,000c88d34beda722f7b559bb056b7809,78064.0,TX,ADMV,A,A,A,N,N,C,...,48.0,A,NaN,2.0,A,NaN,NaN,29.0,201303.0,Hotels and Educational Boarding
9,000cc270c1cc3f09a4a80c2489ce4bac,8401.0,NJ,ADMV,E,A,E,N,Y,-,...,34.0,C,NaN,2.0,B,NaN,NaN,10.0,200309.0,Food and Dining
10,000ea4af96ab938b2612e0b39738e334,7032.0,NJ,ADMV,D,B,B,N,Y,-,...,34.0,B,NaN,2.0,D,NaN,NaN,29.0,201902.0,Manufacturing
11,000f645a52095f72ec723133e2b0092c,45601.0,OH,NaN,D,NaN,A,N,N,C,...,39.0,B,C,2.0,B,NaN,1.0,97.0,202007.0,"Public, Health, and Social Services"
12,00109796f3c34d87f1ff2778498a8016,18330.0,PA,NaN,NaN,NaN,NaN,N,N,NaN,...,42.0,NaN,NaN,2.0,NaN,NaN,NaN,0.0,201909.0,Unknown
13,0012e632be3d04fab35771fe3fb6db31,60467.0,IL,NaN,A,NaN,A,N,N,NaN,...,17.0,A,C,2.0,A,1.0,NaN,16.0,201804.0,Personal Services
14,00130d1949e17227076bc7e4f75139af,43026.0,OH,NaN,A,NaN,A,N,N,NaN,...,39.0,A,NaN,2.0,A,NaN,1.0,67.0,202002.0,Personal Services

In [7]:
#Export to csv
df_firmographic_dropped.to_csv('Clean Data/firmographic_dropped_20230314.csv', index = False)